# This yml is used for PRs, pre-release, and release build.
# We use the github.event_name to determine what started the workflow to determine which
# situation we are in.

name: CI

permissions:
  deployments: write

on:
  pull_request:
    branches:
      - main
      - 'release/*'
  check_run:
    types: [rerequested, requested_action]
  #   push:
  #     branches:
  #       - main
  #       - 'release/*'
  workflow_dispatch:

env:
  NODE_VERSION: 22.15.1
  NPM_VERSION: 10.9.2

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-notebook-renderers'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Use Npm ${{env.NPM_VERSION}}
        run: npm i -g npm@${{env.NPM_VERSION}}

      - run: npm i -g @vscode/vsce

      - run: npm ci
        name: Install dependencies

      - run: npm run lint
        name: 'Lint'

      - run: npm run lint-format
        name: 'Code Format'

      - name: Build VSIX
        run: npm run package

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: 'ms-notebook-renderers.vsix'
          path: 'ms-notebook-renderers.vsix'
